from typing import Any, TypedDict


class LangGraphState(TypedDict):
    # Store the conversation history shared across graph nodes
    messages: list[dict[str, Any]]

    # Store tool calls requested by the latest LLM response
    tool_calls: list[dict[str, Any]]

    # Store the execution plan generated by the planner
    plan: list[str]

    # Track which plan item should be executed next
    current_step: int

    # Store the result produced by each completed plan step
    step_results: list[str]

    # Track how many graph nodes have been executed
    step: int