from typing import Any, TypedDict


class LangGraphState(TypedDict):
    # Store the conversation history shared across graph nodes
    messages: list[dict[str, Any]]

    # Store tool calls requested by the latest LLM response
    tool_calls: list[dict[str, Any]]

    # Store the execution plan generated by the planner
    plan: list[str]

    # Track which plan item should be executed next
    current_step: int

    # Store results produced by completed plan steps
    step_results: list[str]

    # Store whether the current plan step passed review
    step_success: bool

    # Store feedback when the current step needs replanning
    review_feedback: str

    # Track how many times the workflow has replanned
    replan_count: int

    # Track how many graph nodes have been executed
    step: int