from typing import Any, TypedDict
from day03_python_engineering.observability.trace import AgentTrace
from day03_python_engineering.workflow.plan import PlanStep
class LangGraphState(TypedDict):
    # Store the original request for the current workflow execution
    original_request: str

    # Store messages used internally during the current workflow execution
    messages: list[dict[str, Any]]

    # Store clean user-assistant conversation context for LLM context building
    conversation_messages: list[dict[str, Any]]

    # Store tool calls requested by the latest LLM response
    tool_calls: list[dict[str, Any]]

    # Store the structured execution plan generated by the planner
    plan: list[PlanStep]

    # Track which plan item should be executed next
    current_step: int

 

    # Store whether the current plan step passed review
    step_success: bool

    # Store feedback when the current step needs replanning
    review_feedback: str

    # Track how many times the workflow has replanned
    replan_count: int

    # Track how many graph nodes have been executed
    step: int

    # Store the user's approval decision after an interrupt
    approval: bool

    # Store whether the current plan requires human approval
    requires_approval: bool

    # Store the tool names selected by the planner
    tool_names: list[str]

    # Store observability data for this workflow execution
    trace: AgentTrace

    # Store the latest tool execution status
    last_tool_success: bool | None

    # Store long-term user memory separately from conversation context
    user_memory: str